version: '3.8'
services:
  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
